### ISSUE TITLE
Replacing heatshrink with heatshrink2

### ISSUE THREAD

**Issue by Noeljunior** [CharlesWillis3/OctoPrint-MarlinBft#10]
heatshrink looks dead by now, https://github.com/johan-sports/pyheatshrink/issues/17.

Here's a maintained fork of heatshrink2 with support for python3: https://github.com/eerimoq/pyheatshrink.

**Comment by Noeljunior** [comment]
I just noticed you are already aware of this as ,

`2020-08-27 10:49:55,356 > Installing collected packages: heatshrink, **heatshrink2**, marlin-binary-protocol, backports.time-perf-counter, OctoPrint-MarlinBft`

Which means this should detect if we are on a python3 or python2 env. This is completely out of my knowledge.

EDITI:
I tried to understand why and/or what needs both heatshrink and heatshrink2 but I have no idea how pip deps work.

**Comment by trippwill** [comment]
heatshrink is used for python2 and heatshrink2 is used for python3. heatshrink2 is python3 only, as far as I'm aware. Because the library to use is determines at runtime (catching an ImportException), both libraries are included in the dependencies.

**Comment by Noeljunior** [comment]
Which makes this plugin non-installable on a python3 octoprint.

It would be nice to let people know MarlinBft in for python 2 installations only.

`Running setup.py install for heatshrink: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /opt/octoprint-venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-18k97zxv/heatshrink/setup.py'"'"'; __file__='"'"'/tmp/pip-install-18k97zxv/heatshrink/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bj6pjcmb/install-record.txt --single-version-externally-managed --compile --install-headers /opt/octoprint-venv/include/site/python3.8/heatshrink
cwd: /tmp/pip-install-18k97zxv/heatshrink/
Complete output (138 lines):
running install
running build
running build_py
creating build
creating build/lib.linux-armv7l-3.8
creating build/lib.linux-armv7l-3.8/heatshrink
copying heatshrink/__init__.py -> build/lib.linux-armv7l-3.8/heatshrink
copying heatshrink/streams.py -> build/lib.linux-armv7l-3.8/heatshrink
running build_ext
building 'heatshrink.core' extension
creating build/temp.linux-armv7l-3.8
creating build/temp.linux-armv7l-3.8/heatshrink
creating build/temp.linux-armv7l-3.8/heatshrink/_heatshrink
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -pipe -fstack-protector-strong -fno-plt -fno-semantic-interposition -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -pipe -fstack-protector-strong -fno-plt -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I. -I./heatshrink/_heatshrink -I/opt/octoprint-venv/include -I/usr/include/python3.8 -c heatshrink/core.c -o build/temp.linux-armv7l-3.8/heatshrink/core.o -std=c99
heatshrink/core.c: In function '__pyx_pf_10heatshrink_4core_7Encoder_7fill':
heatshrink/core.c:4508:38: warning: comparison of integer expressions of different signedness: 'size_t' {aka 'unsigned int'} and 'Py_ssize_t' {aka 'int'} [-Wsign-compare]
4508 |     __pyx_t_5 = ((__pyx_v_total_sunk < __pyx_t_9) != 0);
|                                      ^
heatshrink/core.c: In function 'PyInit_core':
heatshrink/core.c:7279:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
7279 |   __pyx_type_10heatshrink_4core_Writer.tp_print = 0;
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/object.h:746,
from /usr/include/python3.8/pytime.h:6,
from /usr/include/python3.8/Python.h:85,
from heatshrink/core.c:24:
/usr/include/python3.8/cpython/object.h:260:30: note: declared here
260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
|                              ^~~~~~~~
heatshrink/core.c:7283:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
7283 |   __pyx_type_10heatshrink_4core_Reader.tp_print = 0;
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/object.h:746,
from /usr/include/python3.8/pytime.h:6,
from /usr/include/python3.8/Python.h:85,
from heatshrink/core.c:24:
/usr/include/python3.8/cpython/object.h:260:30: note: declared here
260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
|                              ^~~~~~~~
heatshrink/core.c:7287:3: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
7287 |   __pyx_type_10heatshrink_4core___pyx_scope_struct___drain.tp_print = 0;
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/object.h:746,
from /usr/include/python3.8/pytime.h:6,
from /usr/include/python3.8/Python.h:85,
from heatshrink/core.c:24:
/usr/include/python3.8/cpython/object.h:260:30: note: declared here
260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
|                              ^~~~~~~~
heatshrink/core.c: In function '__Pyx__ExceptionSave':
heatshrink/core.c:8219:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
8219 |     *type = tstate->exc_type;
|                     ^~~~~~~~
|                     curexc_type
heatshrink/core.c:8220:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
8220 |     *value = tstate->exc_value;
|                      ^~~~~~~~~
|                      curexc_value
heatshrink/core.c:8221:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
8221 |     *tb = tstate->exc_traceback;
|                   ^~~~~~~~~~~~~
|                   curexc_traceback
heatshrink/core.c: In function '__Pyx__ExceptionReset':
heatshrink/core.c:8228:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
8228 |     tmp_type = tstate->exc_type;
|                        ^~~~~~~~
|                        curexc_type
heatshrink/core.c:8229:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
8229 |     tmp_value = tstate->exc_value;
|                         ^~~~~~~~~
|                         curexc_value
heatshrink/core.c:8230:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
8230 |     tmp_tb = tstate->exc_traceback;
|                      ^~~~~~~~~~~~~
|                      curexc_traceback
heatshrink/core.c:8231:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
8231 |     tstate->exc_type = type;
|             ^~~~~~~~
|             curexc_type
heatshrink/core.c:8232:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
8232 |     tstate->exc_value = value;
|             ^~~~~~~~~
|             curexc_value
heatshrink/core.c:8233:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
8233 |     tstate->exc_traceback = tb;
|             ^~~~~~~~~~~~~
|             curexc_traceback
heatshrink/core.c: In function '__Pyx__GetException':
heatshrink/core.c:8288:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
8288 |     tmp_type = tstate->exc_type;
|                        ^~~~~~~~
|                        curexc_type
heatshrink/core.c:8289:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
8289 |     tmp_value = tstate->exc_value;
|                         ^~~~~~~~~
|                         curexc_value
heatshrink/core.c:8290:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
8290 |     tmp_tb = tstate->exc_traceback;
|                      ^~~~~~~~~~~~~
|                      curexc_traceback
heatshrink/core.c:8291:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
8291 |     tstate->exc_type = local_type;
|             ^~~~~~~~
|             curexc_type
heatshrink/core.c:8292:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
8292 |     tstate->exc_value = local_value;
|             ^~~~~~~~~
|             curexc_value
heatshrink/core.c:8293:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
8293 |     tstate->exc_traceback = local_tb;
|             ^~~~~~~~~~~~~
|             curexc_traceback
heatshrink/core.c: In function '__Pyx__ExceptionSwap':
heatshrink/core.c:11165:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
11165 |     tmp_type = tstate->exc_type;
|                        ^~~~~~~~
|                        curexc_type
heatshrink/core.c:11166:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
11166 |     tmp_value = tstate->exc_value;
|                         ^~~~~~~~~
|                         curexc_value
heatshrink/core.c:11167:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
11167 |     tmp_tb = tstate->exc_traceback;
|                      ^~~~~~~~~~~~~
|                      curexc_traceback
heatshrink/core.c:11168:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
11168 |     tstate->exc_type = *type;
|             ^~~~~~~~
|             curexc_type
heatshrink/core.c:11169:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
11169 |     tstate->exc_value = *value;
|             ^~~~~~~~~
|             curexc_value
heatshrink/core.c:11170:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
11170 |     tstate->exc_traceback = *tb;
|             ^~~~~~~~~~~~~
|             curexc_traceback
error: command 'gcc' failed with exit status 1
----------------------------------------
ERROR: Command errored out with exit status 1: /opt/octoprint-venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-18k97zxv/heatshrink/setup.py'"'"'; __file__='"'"'/tmp/pip-install-18k97zxv/heatshrink/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bj6pjcmb/install-record.txt --single-version-externally-managed --compile --install-headers /opt/octoprint-venv/include/site/python3.8/heatshrink Check the logs for full command output.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`
